version: "3"
services:
  jenkins: 
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - sample-pipeline-net
    volumes:
      - ../../docker-volumes/sample-pipeline/jenkins:/var/jenkins_home
  sonar:
    image: sonarqube:9.9.0-community
    volumes:
      - ../../docker-volumes/sample-pipeline/sonar/conf:/opt/sonarqube/conf
      - ../../docker-volumes/sample-pipeline/sonar/data:/opt/sonarqube/data
      - ../../docker-volumes/sample-pipeline/sonar/extensions:/opt/sonarqube/extensions
      - ../../docker-volumes/sample-pipeline/sonar/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sample-pipeline-net
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar

  postgres:
    image: postgres
    networks:
      - sample-pipeline-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ../../docker-volumes/sample-pipeline/postgresql:/var/lib/postgresql
      - ../../docker-volumes/sample-pipeline/postgresql_data:/var/lib/postgresql/data  

networks:
  sample-pipeline-net:
    driver: bridge

    